[package]
name = "zero"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "zero"
path = "src/main.rs"

[dependencies]
chrono.workspace = true
serde.workspace = true
surrealdb.workspace = true
tokio.workspace = true
dotenvy.workspace = true
rppal.workspace = true
common.workspace = true